language: minimal
git:
  depth: false
addons:
  apt:
    packages:
    - python
env:
  - TARGET=adafruit:samd:adafruit_feather_m0
before_install:
  - make setup
install: true
script:
  - make all
cache:
  directories:
    - .arduino
